packages:
  - apps/*

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - fs-xattr
  - macos-alias
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  'eslint-plugin-react-hooks>zod-validation-error': '4.0.2'
